spring:
  application:
    name: EventFlow
  datasource:
    url: jdbc:postgresql://localhost:5433/event_flow
    username: ivan
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8082